language: node_js
sudo: false
node_js:
- '6'

# cache:
#   directories:
#     - node_modules

# env:
#   - CXX=g++-4.8

install:
  - npm install

script:
  - npm run test
#   - ./node_modules/.bin/karma start --single-run --browsers Firefox --reporters mocha
  # Make sure the build that ships to npm builds without errors
  - npm run build
  # Run integration test to make sure our typings are correct for user-land.
#   - node tools/run-typings-test.js
  # Can't run until https://github.com/angular/protractor/issues/2784 is resolved
  #- ./node_modules/.bin/protractor protractor.conf.js --browser firefox

notifications:
  webhooks:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false