language: node_js
sudo: false
node_js:
- node
addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

branches:
  only:
  - master
  - develop

script:
- npm run test --silent
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false

deploy:
  provider: heroku
  api_key:
    secure: "Vgw4sjM7Y99y7Eeb2y7V3ZXQgmRzGN8Hr2dXXUJNVXKJFcbiZJuXpiloMzGZ+L1ZOqi8qF4qPCmi9lPCnT6XUgjBDi6SeKQbNBUfiBmH7w39KzeC4ZYqU/dvzIZmMFwfrjlKhMZ6feJZ4ND1dzQQXD2Wh649TJdzjy39GbVfsCX798xVGHfRK37pd8W/4Vd5tJFgYYUeYbvRuQ8duiPf6rbQ/vJL01MOhel3d0M4hhjqf5UvEwagcHgFjWb3AXeQFUvMQMt1jSR/izfayCu9gIWeZ2AWhlvEUKPxmCJqauf6sUWgJD6fJrbDshU48nnmhxo7w2eEzNyGMTZ6a8LLbncjMMcUPV8CEOB3YFYgRM2/lHtaagOl44zaJ7eza5MWa5p/DV4UG91Pev5kz5dQ4hxq+Y/WoTib/gxBkdOCbH/NEttHNpfyVt4JDkqHTmYma5ByqBW8O6JcB2EqYF6v29SplbAB9wj5+wZEO/CvVBDpfrHXthjiSu7EiY10BJ5LBlFWeoQ/RPYen5yn9vqGP3Ihs/uzMjtTb3UOfeqLWHv7doj4U/SdyPaOFuNFonnSltAElV7qEa14A165XK4d6cstwNAFAFb567xEeBXDRPrxDq94rkfCukMyIG8Qqu7YqMG3qmr3ip7ieIwFGo1JxK1i8DJwKK0rbQMO0Me0fMM="
    app: arcane-headland-21979
    on:
      branch: master
