language: node_js
sudo: false
node_js:
- node
addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run test --silent
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false

deploy:
  provider: heroku
  api_key: 988f0e76-6418-4ca3-a769-29d2bf54dfc9
  app: arcane-headland-21979
  on:
    branch: master
